MozillaSocial/elk

components/modal/ModalContainer.vue
pages/settings/about/index.vue

Removes Elk Preview dialog that displays on first visit.  Also removes related settings control that triggers the same dialog.  
Comment used to disable dialog in case we want to re-enable with Mozilla.social branded welcome or similar.

Mztdn 155/remove first visit dialog

---

nuxt.config.ts

Get elk running without it having to be on `/elk` 
This requires getting the env variables working on stage and merging https://github.com/mozilla-services/mozsocial-haproxy-router/pull/3

feat(/elk): removing /elk for cleaner urls

---

nuxt.config.ts

Masto is used on pre-rendering lists. Disabling that for now.

fix(prerender): remove the pre-rendering of lists since it uses masto

---

locales/en.json

[SOCIALPLAT-461](https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-461)
Rename
Before:
After:

fix(settings): Rename Account Settings to Advanced Settings

---

locales/en.json
pages/settings.vue
pages/settings/language/index.vue
pages/settings/notifications/index.vue
pages/settings/profile/index.vue

[SOCIALPLAT-465](https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-465)
I did not remove any pages or functions related to these buttons as it seemed like there's a chance some may come back (plus we're not doing any unnecessary cleanup for the ASAP phase)

fix(settings): remove unneeded elk settings

---

error.vue
locales/en.json
pages/home.vue

[SOCIALPLAT-396](https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-396)
**Some things I'd like some help on**:
1. I'm seeing a FOUC _sometimes_ when navigating back and forth between the 404 page and other pages. It doesn't happen every time and I can't nail down why it's happening.
- Update: After some additional investigating and chatting with @collectedmind, we've decided to not focus on fixing the FOUC right now. It's unclear whether this is an issue that will occur in the staging and production environments or is simply happening on localhost. Once this is deployed, we can do additional testing and investigate further if needed.  
3. I tried a few different ways to force a 500 error so I could test it, but I wasn't able to find a good one, so I just threw a javascript error in the …

fix(error pages): add specific copy for 404 & 500 errors

---

constants/themes.json
scripts/generate-themes.ts
styles/default-theme.css
styles/vars.css

Adds dark purple (for light mode) and light purple (for dark mode) as the default colors for our Elk instance.
Also fixes a bug where Dark Mode wasn't actually using the Dark Mode colors - this can be upstreamed.

Change default color to Mozilla accents

---

components/main/MainContent.vue
components/nav/NavFooter.vue
unocss.config.ts

Wanted to explore how easy it was to convert custom styles to UnoCSS attributes. Turns out, it's not too terrible. I've documented some learnings below and I would love to do a brownbag/lunch & learn about UnoCSS after all hands.
<details>
<summary>Some Learnings:</summary>
- Custom styles are possible (if you know the magic incantations 🪄 )
- `width: 212px` becomes `w-212px`
- `border-radius: 8px` becomes `b-rd-8px`
- I think a good rule of thumb is that if there is a unit (`px`, `rem`, `em`), then it's a custom value
- Variables are a-ok but a little confusing (still wrapping my head around how it all works)
- UnoCSS does provide quite a bit of customization via the [config](https://unocss.dev/guide/config-file)
- The [interactive docs](https://unocss.dev/interactive/) are often …

fix(beta labels): move styles to unocss data attributes

---

unocss.config.ts

[SOCIALPLAT-506](https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-506)
Okay fine, I'll let you have this one UnoCSS. Shortcuts are cool.

fix(unoCSS config): update text color for btn-solid shortcut

---

components/user/UserSignInEntry.vue
composables/sign-in.ts
locales/en.json

Splits the original Sign In button into "Create account" and "Sign in". Both lead to FxA, but create account sets a "signup" intent which causes an interstitial to show.
Also tidied copy and design, as per https://www.figma.com/file/wcdvUdM6RBsQ8hryI2iNlB/ASAP-Elk-Update?node-id=238%3A4793&mode=dev

Add Create Account button

---

components/status/StatusActionsMore.vue
components/status/StatusLink.vue
composables/masto/routes.ts
nuxt.config.ts

The copy link functionality was doubling up and making copied links invalid. This adjust things so links behave as expected
There was some hoop jumping to generate a link that were (it seems) a remnant of multi-client setup.  Things worked fine locally, but when we put things behind a proxy, some built in redirects broke down.
This uses the built in status link to generate a valid link.  Hard to know what the original intent was given the nature of the repo.
Would love to know if anyone more familiar with this code base to make sure this will not destroy the entire world as we know it.  Dogs and cats, living together ... mass hysteria!

fix(status actions): adjust original link generation

---

components/main/MainContent.vue
components/nav/NavUser.vue

[SOCIALPLAT-555](https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-555)
Mobile view cannot create accounts.
This PR adds a new "Create account" button to the mobile header and adjusts the styling of the existing "Sign In" button.
The new button functions the same way as the [desktop view button added by Ashwin](https://github.com/MozillaSocial/elk/pull/32).
Moiz and I worked together to figure out the sidebar-less version over Zoom
Tablet:
Mobile:
______________________________________________________
Lesser cool duck-less pictures of light mode:
Tablet:
Mobile:
- How satisfied are you with UnoCSS on a scale from 1-5?

Introduce 'Create account' button on mobile view

---

locales/en.json
pages/settings/profile/index.vue

[SOCIALPLAT-600](https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-600)

fix(account settings): add link to mozilla social settings

---

components/timeline/TimelineDiscover.vue
composables/recommendations.ts
locales/en.json
modules/tauri/runtime/nitro.client.ts
pages/discover.vue
server/api/recommendations.ts
utils/language.ts

Adding an API endpoint to fetch recommendations and call that API from within an empty discover page
Needed to add an internal API endpoint instead of hitting the recs endpoint directly to fetch recs to prevent any CORS issues
- https://mozilla-hub.atlassian.net/browse/SOC-43
- https://mozilla-hub.atlassian.net/browse/SOC-44

feat(recs): add recs api call and empty discover page [SOC-43, SOC-44]

---

components/account/AccountMoreButton.vue
composables/masto/routes.ts

[SOCIALPLAT-561](https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-561)
Before:
- command-click on Account name or profile pic would lead to a broken link
- on local (Mozilla Social) account pages, clicking the "three dots" would bring up a menu that had "Open in original site" option", which would just lead you back to the same page
After:
- command-click no longer results in broken link
- three dot menu hides the "original site" option when you are viewing a local account (remains unchanged for remote accounts)

Fix account route; remove Original Site option for local accounts

---

components/timeline/TimelineDiscover.vue

Adding the template so we can display recommendations on Discover
[Jira ticket](https://mozilla-hub.atlassian.net/browse/SOC-46)
Took some liberties with the [Figma design](https://www.figma.com/file/QquqdFHNTs8E5ZgW6VImGL/Moz-Social---Design-System-Library-(Working-File)?type=design&node-id=520-6304&mode=design&t=88IIbVNfmcJQh7Tp-0) so it could use the unocss shorthand.
If we need to we can pull the Recommendation specific template into a separate component, but I figured this was a good way to get it on the page so people can start playing with it.

fix(discover): adding template for recommendation cards [SOC-46]

---

locales/en.json

Update any text and images that reference Firefox Accounts in preparation for the FxA -> MozA rebrand [SOC-120](https://mozilla-hub.atlassian.net/browse/SOC-120)
Before:
After:

fix(fxa): update settings language to remove Firefox [SOC-120]

---

composables/masto/translate.ts

I was poking around translation-related things and discovered this [old commit](https://github.com/elk-zone/elk/pull/1371/commits/646248f078a68f857264bfafb41b2f1c97c8f8f5) from upstream that I think introduced a bug with `shouldTranslate` behavior.
Figured I'd open a PR to revert that change and hide the translate button, since we don't know have a roadmap for adding translation yet.

fix(UI): hide Translate Post button if a translation API endpoint isn't specified

---

components/timeline/TimelineDiscover.vue
server/api/[server]/recommendations.ts

Update API endpoint to return images and removed the UTM param helper function
I updated the API to include image info as laid out in the [spec](https://github.com/MozillaSocial/content-feed-service/blob/main/spec/openapi-moso-discover.yml)

fix(recommendations): update the recs api to pass back image info and remove utm parse function

---

components/recommendation/RecommendationArticle.vue
components/timeline/TimelineDiscover.vue

Prep recommendations to send analytics events
My work with the intersection observer was based on the [@vueuse/core](https://vueuse.org/core/useIntersectionObserver/) package.

fix(recommendations): prepping recommendations to fire impression events for analytics

---

components/recommendation/RecommendationArticle.vue

Update text limits from character limits to line limits
The request was to remove all limits from the Title, as that is automatically truncated on the server to 255 characters.
The description needs to be clamped to a maximum of 3 lines.

fix(discover): add line limits to recommendations over character limits [MS-59]

---

components/recommendation/RecommendationArticle.vue
composables/recommendations.ts
telemetry/engagementDetails.ts

Adding glean events for impression, open, and share actions
Worked with Aly on this, followed existing patterns

fix(discover): add impression, click, and share events [MOSOWEB-48, MOSOWEB-58]

---

components/account/AccountHeader.vue
components/account/AccountMoreButton.vue
components/settings/SettingsColorMode.vue
components/settings/SettingsFontSize.vue
components/settings/SettingsThemeColors.vue
telemetry/engagementDetails.ts
telemetry/engagementProfileEvents.js

While reviewing #67 I noticed that we had a mix of cases when it came to naming our engagement events, so I reached out to the data analytics team to see if they had a preference. They [decided](https://mozilla.slack.com/archives/C05EBRU3V1U/p1697749553620799) on `kebab-case`, so this PR simply updates the existing engagement events, plus those in #67, to be consistent. Two other small changes called out in comments.
This PR is to be merged into #67.

fix(glean): rename events to use kebab case

---

telemetry/engagementDetails.ts

Updating the engagement type for this action to `share` instead of `general`

fix(discover): update engagement type for discover share action

---

.github/workflows/ci.yml
package.json

Add Glean linter to pre-commit check
😎

fix(glean): adding glean linter to pre commit hook [MOSOWEB-41]

---

modules/glean/runtime/glean-plugin.client.ts

Goal: clicking on any part of a link should trigger engagement events.
Currently, our code is not setup to handle clicks on children of an anchor `<a>` tag.
This PR is a follow up improvement to https://github.com/MozillaSocial/elk/pull/67#discussion_r1368881577
Image showing the bounding box of a nested `<span>` in an `<a>`

fix(analytics): capture engagement events on children of <a>'s

---

components/status/StatusLink.vue
telemetry/engagementDetails.ts
telemetry/engagementPostEvents.js

Goal: When a user clicks a link within a post, we need to log an engagement event. [MOSOWEB-49
](https://mozilla-hub.atlassian.net/browse/MOSOWEB-49)
Example of a post with a link
Engagement event showing up in Debug Ping Viewer

fix(posts): track when users click links within posts [MOSOWEB-49]

---

components/publish/PublishAttachment.vue
components/status/StatusAttachment.vue
locales/en.json

[MOSOWEB-25](https://mozilla-hub.atlassian.net/browse/MOSOWEB-25?atlOrigin=eyJpIjoiMjk0MWI3ZWJhM2JiNDc2ZGFiNGE3YTkwZmVmZTlhOWQiLCJwIjoiaiJ9)

feat: Image upload improvements  [MOSOWEB-25]

---

components/status/StatusActions.vue
components/status/StatusActionsMore.vue
components/status/StatusCard.vue
components/timeline/TimelineBookmarks.vue
components/timeline/TimelineFavourites.vue
components/timeline/TimelineHome.vue
components/timeline/TimelinePaginator.vue
components/timeline/TimelinePublic.vue
components/timeline/TimelinePublicLocal.vue
pages/[[server]]/@[account]/index/index.vue
telemetry/engagementDetails.ts
telemetry/engagementPostEvents.js

Adding glean events for Post Button interactions (Like, Boost, Respond, Share, Report)
[MOSOWEB-44](https://mozilla-hub.atlassian.net/browse/MOSOWEB-44)
* Did I miss any other feeds?
* Should I rename "post.reblog" to "post.boost" to match the `engagement_type`?
```
"ui_identifier": "post.reblog",
"mastodon_status_id": "111330231322029109",
"engagement_type": "boost"
```
The feed names are defined in the "Timeline" components. I did some light prop drilling instead of doing something involving the page URL.
For example, here's Home
```
<TimelineHome feedName="home.feed">
<TimelinePaginator feedName>
<StatusCard feedName>
<StatusActionsMore feedName>     <--- Report
<StatusActions feedName>         <--- Like/boost/reply/bookmark
```
5 action types, multiplied by the 4 feeds + standalone …

fix(posts): Post Button interactions (Like, Boost, Respond, Share, Report) [MOSOWEB-44]

---

components/publish/PublishWidget.vue
components/publish/PublishWidgetFull.client.vue
components/timeline/TimelineHome.vue
telemetry/engagementDetails.ts

MOSOWEB-46 https://mozilla-hub.atlassian.net/browse/MOSOWEB-46
All post creations, replies and edits should have an analytics action associated.
Send the following Engagement Event:
```
engagement event
ui_identifier is post.create (or something like that)
Includes a mastodon_status_id that we can cross-reference against prod data
engagement_type is post
```
- Do I buy [Lego 10305 - Lion Knights' Castle](https://www.lego.com/en-us/product/lion-knights-castle-10305)? Non-Star Wars building sets are suddenly really enticing to me.
- The oddball in the list of new events, `home.post.create`, is a decision from Kirill
- home.post.create
- post.create
- post.edit
- post.reply

fix(post): post creation interactions [MOSOWEB-46]

---

components/nav/NavBottom.vue
components/nav/NavSide.vue

Updating the icon for the Discover page
Verified with Moiz that it's a good one

fix(discover): update discover icon [MOSOWEB-88]

---

app.vue
components/common/CommonPaginator.vue
components/nav/NavTitle.vue
locales/de-DE.json
locales/en.json
nuxt.config.ts

Anywhere it's visible to the user, replace `elk` with `Mozilla.social`. [MOSOWEB-98](https://mozilla-hub.atlassian.net/browse/MOSOWEB-98)
* Per Laurie, I only focused on the English & German translations
* There are 1154 references to `elk` in the repo. Most of these are in documentation, config, constants, translations (that aren't supported) and dead components. I was pretty thorough in my chasing down of anything that might be visible to the user, and I think I've covered everything

fix(rename): replace Elk with Mozilla.social - MOSOWEB-98

---

locales/de-DE.json
locales/en.json

Replace "Elk" text from Push Notifications settings with "Mozilla.social" [MOSOWEB-89](https://mozilla-hub.atlassian.net/browse/MOSOWEB-89)
Image of the affected spot in local:
I did some stuff in `components/notification/NotificationPreferences.client.vue` and `pages/settings/notifications/push-notifications.vue` to force my way into the route :shrug:
Something about `pwaEnabled` disallows this page in local

fix(settings): change elk to moz social in notifications settings [MOSOWEB-89]

---

.github/workflows/glean-probe-scraper.yml

This implements the last step described in [the Glean Book](https://mozilla.github.io/glean/book/user/adding-glean-to-your-project/enable-data-ingestion.html#validate-and-publish-metrics).
Note that the application is [already added](https://dictionary.telemetry.mozilla.org/apps/moso_mastodon_web), but will only show the default metrics until this PR is merged.

chore(glean): finalize adding elk to the Glean pipeline

---

constants/index.ts
server/utils/shared.ts

[MOSOWEB-90](https://mozilla-hub.atlassian.net/browse/MOSOWEB-90)
Bug: When you post on mozilla.social, your post gets a label that says “Elk” and links to “elk.zone”.
Posts have an `application` field with `name` and `website` data. `application` refers to an instance of [Application](https://docs.joinmastodon.org/entities/Application/)
```
status.application.name: "Elk"
status.application.website: "https://elk.zone/"
```
Change the application `name` and `website` fields. This PR is a frontend fix to a fetch call. Backend will do a fix to actually update `name` and `website`

fix(config): change application name and website [MOSOWEB-90]

---

modules/glean/runtime/glean-plugin.client.ts
pages/settings.vue

Enable Glean in production so we can start tracking analytics
[SOCWEB-145](https://mozilla-hub.atlassian.net/browse/SOCWEB-145)
Right now, this enables Glean for _all_ environments (dev, staging and production). @kirill-demtchouk you should be able to filter the events based on environment via the `channel` that we send through, but I am open to adjusting this so it's not uploading events for all environments. Let me know your thoughts!

feat(glean): enable glean in prod - SOCWEB-145

---

modules/glean/runtime/glean-plugin.client.ts

Per Kirill's request, we are adding a prefix to the `app_channel` that we send to glean so the data team will be able to differentiate between elk & aquatic.

fix(glean): prefix app channel

---

components/status/StatusContent.vue
components/status/StatusPreviewCardNormal.vue

This just uses blurhash on images in preview cards that are found in posts marked as sensitive.
We still don't blurhash images in posts that contain content warnings. So if we show more content on a post there is no clear way of knowing if it contains sensitive images...

fix(preview card): blurhash on sensitive content 

---

components/report/ReportModal.vue
components/status/StatusActionsMore.vue
locales/en.json

- Anonymous users will see the option to report user or post
- When an anonymous user submits a post, it’ll go to a different endpoint
- Does user needs to add their email for follow-up? 
We need to add an option to report a potential post/user violation anonymously aka violations reporting for logged out users. 
This is ESSENTIAL for us to meet EU’s DSA deadline of Feb 17.

feat(report): allow anonymous reporting [SOCWEB-197]
